export const mockBusinessHourDetails = [
  {
    id: 1,
    barId: 1,
    dayOfWeek: 'mon',
    openTime: '18:00',
    closeTime: '02:00',
    isClosed: false,
    significant: '월요일 특별 이벤트',
  },
  {
    id: 2,
    barId: 1,
    dayOfWeek: 'tue',
    openTime: '18:00',
    closeTime: '02:00',
    isClosed: false,
    significant: '',
  },
  {
    id: 3,
    barId: 1,
    dayOfWeek: 'wed',
    openTime: '18:00',
    closeTime: '02:00',
    isClosed: false,
    significant: '수요일 라이브 음악',
  },
  {
    id: 4,
    barId: 1,
    dayOfWeek: 'thu',
    openTime: '18:00',
    closeTime: '02:00',
    isClosed: false,
    significant: '목요일 칵테일 타임',
  },
  {
    id: 5,
    barId: 1,
    dayOfWeek: 'fri',
    openTime: '18:00',
    closeTime: '03:00',
    isClosed: false,
    significant: '금요일 파티 나이트',
  },
  {
    id: 6,
    barId: 1,
    dayOfWeek: 'sat',
    openTime: '20:00',
    closeTime: '04:00',
    isClosed: false,
    significant: '토요일 DJ 파티',
  },
  {
    id: 7,
    barId: 1,
    dayOfWeek: 'sun',
    openTime: '19:00',
    closeTime: '01:00',
    isClosed: false,
    significant: '일요일 휴식의 시간',
  },
  {
    id: 8,
    barId: 2,
    dayOfWeek: 'mon',
    openTime: '',
    closeTime: '',
    isClosed: true,
    significant: '월요일 휴무',
  },
  {
    id: 9,
    barId: 2,
    dayOfWeek: 'tue',
    openTime: '19:00',
    closeTime: '01:00',
    isClosed: false,
    significant: '',
  },
  {
    id: 10,
    barId: 2,
    dayOfWeek: 'wed',
    openTime: '19:00',
    closeTime: '01:00',
    isClosed: false,
    significant: '수요일 와인 테이스팅',
  },
  {
    id: 11,
    barId: 2,
    dayOfWeek: 'thu',
    openTime: '19:00',
    closeTime: '01:00',
    isClosed: false,
    significant: '',
  },
  {
    id: 12,
    barId: 2,
    dayOfWeek: 'fri',
    openTime: '19:00',
    closeTime: '02:00',
    isClosed: false,
    significant: '금요일 프리미엄 칵테일',
  },
  {
    id: 13,
    barId: 2,
    dayOfWeek: 'sat',
    openTime: '20:00',
    closeTime: '03:00',
    isClosed: false,
    significant: '토요일 스페셜 이벤트',
  },
  {
    id: 14,
    barId: 2,
    dayOfWeek: 'sun',
    openTime: '18:00',
    closeTime: '00:00',
    isClosed: false,
    significant: '일요일 얼리 클로징',
  },
]
