import { faker } from '@faker-js/faker'

export const mockReviews = [
  {
    id: 1,
    bar_id: 1,
    user_name: '김바텐',
    profile_image: faker.image.avatar(),
    visit_date: '2025-08-15',
    rating: 5,
    comment: '칵테일 맛도 훌륭하고 바텐더가 정말 친절했어요!',
    created_at: '2025-09-20T12:34:56Z',
    like_count: 18,
    images: [faker.image.urlLoremFlickr({ category: 'food' })],
    tags: ['친절해요', '분위기좋아요', '재방문의사있음'],
  },
  {
    id: 2,
    bar_id: 1,
    user_name: '이밤',
    profile_image: null,
    visit_date: '2025-09-01',
    rating: 4,
    comment: '조용하고 좋았는데 좌석이 약간 불편했어요.',
    created_at: '2025-09-22T09:11:03Z',
    like_count: 7,
    images: null,
    tags: ['조용한분위기', '가성비굿'],
  },
  {
    id: 3,
    bar_id: 2,
    user_name: 'Park',
    profile_image: faker.image.avatar(),
    visit_date: '2025-09-10',
    rating: 3,
    comment: '전반적으로 무난. 하이볼은 괜찮았어요.',
    created_at: '2025-09-23T19:45:12Z',
    like_count: 3,
    images: [faker.image.urlLoremFlickr({ category: 'drink' })],
    tags: ['무난해요'],
  },
  {
    id: 4,
    bar_id: 3,
    user_name: 'Jin',
    profile_image: faker.image.avatar(),
    visit_date: '2025-09-18',
    rating: 5,
    comment: '생일 이벤트로 갔는데 음악과 조명이 최고!',
    created_at: '2025-09-24T21:02:40Z',
    like_count: 25,
    images: null,
    tags: ['생일추천', '라이브좋아요', '인테리어예쁨'],
  },
  {
    id: 5,
    bar_id: 4,
    user_name: 'Sora',
    profile_image: null,
    visit_date: '2025-09-20',
    rating: 2,
    comment: '기대보다 시끄러웠고 예약 확인이 늦었어요.',
    created_at: '2025-09-25T08:27:19Z',
    like_count: 1,
    images: [faker.image.urlLoremFlickr({ category: 'nightlife' })],
    tags: ['시끄러움', '대기있음'],
  },
]
